version: '3.8'

services:
  postgres:
    image: postgres:latest  
    container_name: shortnener_url
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortnenerUrl
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: